"""
Generate full UNPIVOT SQL for M5 sales data
Covers all 1,941 days in the dataset
"""

# Generate all day column names
days = ", ".join([f"d_{i}" for i in range(1, 1942)])

sql = f"""
-- Full unpivot of M5 sales data (1,941 days)
-- Generated by generate_unpivot_sql.py
-- Run this directly in BigQuery console

CREATE OR REPLACE TABLE `walmart_forecasting.raw_sales_train_unpivot` AS
WITH unpivoted AS (
    SELECT
        id,
        item_id,
        dept_id,
        cat_id,
        store_id,
        state_id,
        day_id,
        CAST(sales AS INT64)                        AS sales
    FROM `walmart_forecasting.raw_sales_train`
    UNPIVOT(
        sales FOR day_id IN ({days})
    )
)

SELECT
    id,
    item_id,
    dept_id,
    #cat_id,
    store_id,
    #state_id,
    day_id,
    sales,

    -- Parse day number for sales feature (lag, order by)
    CAST(SPLIT(day_id, '_')[OFFSET(1)] AS INT64)    AS day_num,

    -- Item hierarchy
    cat_id                                          AS category,
    SPLIT(dept_id, '_')[OFFSET(1)]                  AS department,
    SPLIT(item_id, '_')[OFFSET(2)]                  AS item,


    -- Store hierarchy
    state_id                                        AS State,
    SPLIT(store_id, '_')[OFFSET(1)]                 AS store_number,

    -- no sales on that item on that day flag
    CASE WHEN sales = 0 THEN 1 ELSE 0 END           AS is_no_sales

FROM unpivoted;
"""

# Save SQL to file
output_path = "ingestion/stg_sales_unpivot.sql"
with open(output_path, "w") as f:
    f.write(sql)

print(f"   SQL generated: {output_path}")
print(f"   Total days:    {len(days.split(','))}")
print(f"   Total chars:   {len(sql):,}")
print()
print("Next step:")
print("  1. Open ingestion/stg_sales_unpivot.sql")
print("  2. Copy the SQL")
print("  3. Paste into BigQuery console and run")