version: 2

sources:
  - name: walmart_raw
    database: walmart-demand-intelligence
    schema: walmart_forecasting
    tables:
      - name: raw_calendar
      - name: raw_sales_train
      - name: raw_sell_prices
      - name: raw_sales_train_unpivot