name: 'walmart_dbt'
version: '1.0.0'
config-version: 2

profile: 'walmart_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  walmart_dbt:
    staging:
      +materialized: table
    marts:
      +materialized: table
    features:
      +materialized: table
